{{- if .Values.ingress.certManager.enabled }}
{{- if not .Values.ingress.certManager.clusterIssuer }}
{{- $fullName := include "freelight-landing.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullName }}-landing-issuer
spec:
  acme:
    email: {{ .Values.ingress.certManager.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ $fullName }}-landing-private-key
    solvers:
    - selector: {}
      {{- if eq .Values.ingress.certManager.solver "dns01" }}
      dns01:
        {{- toYaml .Values.ingress.certManager.dns01 | nindent 8 }}
      {{- else }}
      http01:
        ingress:
          class: {{ .Values.ingress.className }}
      {{- end }}
{{- end -}}
{{- end -}}
