#!/usr/bin/env bash

ENV=$1
NAMESPACE=${2:-"$ENV"}

if [ "$ENV" == "" ]; then
    echo "Please specify the environment: ./install-valkey.sh staging"

    exit 1
fi

if [ ! -f "./.env" ]; then
  echo ".env file is missing."

  exit 1
fi

source ./.env

KUBECONFIG_STR=""

if [ "$KUBECONFIG_PATH" != "" ]; then
  KUBECONFIG_STR="--kubeconfig $KUBECONFIG_PATH"
fi

AUTH_STR=""

if [ "$VALKEY_AUTH" != "" ]; then
  AUTH_STR="--set global.valkey.password=${VALKEY_AUTH}"
fi

TLS_STR=""

if [ "$VALKEY_TLS" == "1" ]; then
  TLS_STR="--set tls.enabled=true --set tls.autoGenerated=true"
fi

# Install Valkey
helm repo add bitnami https://charts.bitnami.com/bitnami
helm update

echo "Installing Valkey $VALKEY_VERSION"

helm $KUBECONFIG_STR upgrade --install valkey oci://registry-1.docker.io/bitnamicharts/valkey --version=$VALKEY_VERSION \
    --namespace $NAMESPACE --create-namespace \
    --set architecture=standalone ${TLS_STR} \
    --set primary.persistence.enabled=false

echo "Finished installing Valkey..."
