apiVersion: v1
kind: ConfigMap
metadata:
  name: gluetun-iptables-post-rules
  namespace: cattle-system
data:
  post-rules.txt: |
    # Ensure Kubernetes Service CIDR uses main routing table (eth0)
    iptables -t mangle -I OUTPUT 1 -d XXX -j MARK --set-mark 0
    
    # Ensure Pod / Node CIDR uses main routing table (eth0)
    iptables -t mangle -I OUTPUT 1 -d XXX -j MARK --set-mark 0
