{{- $databaseServer := .Values.freelightDAO_API.database.server -}}
{{- if .Values.database.deploy -}}
{{- $databaseServer = include "freelight-dao.serviceAccountName" . -}}
{{- $databaseServer = print $databaseServer "-db-service" -}}
{{- end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freelight-dao.fullname" . }}
  labels:
    {{- include "freelight-dao.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "freelight-dao.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "freelight-dao.selectorLabels" . | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imageSettings.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imageSettings.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "freelight-dao.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: freelight-dao-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: busybox:1.36
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for database to be ready at {{ $databaseServer }}:{{ .Values.freelightDAO_API.database.port }}"
              while ! nc -z {{ $databaseServer }} {{ .Values.freelightDAO_API.database.port }}; do
                sleep 1
              done
              echo "Database ready"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      containers:
        - name: freelight-dao-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.freelightDAO_API.image }}"
          imagePullPolicy: {{ .Values.imageSettings.pullPolicy }}
          ports:
            - name: api
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: api
          readinessProbe:
            httpGet:
              path: /
              port: api
          env:
            - name: SERVER_TYPE
              value: "api"
            - name: LOG_LEVEL
              value: "{{ .Values.freelightDAO_API.logLevel }}"
            - name: API_HTTP_PORT
              value: "5000"
            - name: BASE_API_URL
              value: "{{ .Values.freelightDAO_API.baseApiUrl }}"
            - name: JWT_SECRET_KEY
              value: "{{ .Values.freelightDAO_API.jwtSecretKey }}"
            - name: RECAPTCHA_KEY
              value: "{{ .Values.freelightDAO_API.recaptchaKey }}"
            - name: DATABASE_SERVER
              value: "{{ $databaseServer }}"
            - name: DATABASE_PORT
              value: "{{ .Values.freelightDAO_API.database.port }}"
            - name: DATABASE_USERNAME
              value: "{{ .Values.freelightDAO_API.database.username }}"
            - name: DATABASE_PASSWORD
              value: "{{ .Values.freelightDAO_API.database.password }}"
            - name: DATABASE_SCHEMA
              value: "{{ .Values.freelightDAO_API.database.schema }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
