apiVersion: v1
kind: Service
metadata:
  name: {{ include "freelight-dao.fullname" . }}
  labels:
    {{- include "freelight-dao.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "freelight-dao.selectorLabels" . | nindent 4 }}
