{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freelight-dao.serviceAccountName" . }}-api-sa
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "api") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- if .Values.dicebear.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freelight-dao.serviceAccountName" . }}-dicebear-sa
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "dicebear") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.freelightDAO_frontend.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freelight-dao.serviceAccountName" . }}-frontend-sa
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "frontend") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.garnetPubSub.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freelight-dao.serviceAccountName" . }}-garnet-pubsub-sa
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "garnet-pubsub") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.garnet.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freelight-dao.serviceAccountName" . }}-garnet-sa
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "garnet") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- if .Values.database.deploy }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "freelight-dao.serviceAccountName" . }}-db-sa
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "db") .) | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
{{- end }}
