{{- if eq .Values.freelightDAO_API.fileStorage.location "local" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "freelight-dao.fullname" . }}-api-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.freelightDAO_API.data.size }}
  storageClassName: {{ .Values.freelightDAO_API.data.storageClassName }}
{{- end -}}