{{- if .Values.freelightDAO_frontend.enabled -}}
{{- if .Values.freelightDAO_frontend.useConfigMap -}}
{{- $apiUrl := .Values.freelightDAO_API.baseApiUrl -}}
{{- $webUrl := .Values.freelightDAO_API.baseWebUrl -}}
{{- $wsUrl := ternary (regexReplaceAll "^https://" $apiUrl "wss://") (regexReplaceAll "^http://" $apiUrl "ws://") (hasPrefix "https://" $apiUrl) -}}
{{- $frontendHost := index .Values.freelightDAO_frontend.httpRoute.hostnames 0 -}}
{{- $cookiesDomain := regexReplaceAll "^[^.]*" $frontendHost "" -}}
{{- $diceBearUrl := "" -}}
{{- if .Values.dicebear.deploy -}}
{{- $diceBearUrl = printf "https://%s" (index .Values.dicebear.httpRoute.hostnames 0) -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |-
    {
      "baseUrl": {{ $apiUrl | quote }},
      "wsUrl": {{ $wsUrl | quote }},
      "diceBearUrl": {{ $diceBearUrl | quote }},
      "cookiesDomain": {{ $cookiesDomain | quote }},
      "paypalDonateUrl": {{ printf "%s/donate.html" $webUrl | quote }},
      "header": {
        "TITLE": {{ default "FreeLight DAO" .Values.freelightDAO_frontend.title | quote }},
        "PANEL_NAME": {{ default "FreeLight DAO" .Values.freelightDAO_frontend.title | quote }},
        "SIDEBAR_ITEMS": [
          {
            "url": "/users",
            "icon": "<span data-feather=\"user\" class=\"align-text-bottom\" id = \"Header_Users\"></span>",
            "label": "Users"
          },
          {
            "url": "/proposals",
            "icon": "<span data-feather=\"coffee\" class=\"align-text-bottom\" id = \"Header_Proposals\"></span>",
            "label": "Proposals"
          },
          {
            "url": "/projects",
            "icon": "<span data-feather=\"book-open\" class=\"align-text-bottom\" id = \"Header_Projects\"></span>",
            "label": "Projects"
          },
          {
            "url": "/bankAccounts",
            "icon": "<span data-feather=\"briefcase\" class=\"align-text-bottom\" id = \"Header_BankAccounts\"></span>",
            "label": "Bank Accounts"
          },
          {
            "url": "/budgets",
            "icon": "<span data-feather=\"folder\" class=\"align-text-bottom\" id = \"Header_Budgets\"></span>",
            "label": "Budgets"
          },
          {
            "url": "/expenses",
            "icon": "<span data-feather=\"bar-chart-2\" class=\"align-text-bottom\" id = \"Header_Expenses\"></span>",
            "label": "Expenses"
          },
          {
            "url": "/income",
            "icon": "<span data-feather=\"dollar-sign\" class=\"align-text-bottom\" id = \"Header_Income\"></span>",
            "label": "Income"
          },
          {
            "url": "/agreements",
            "icon": "<span data-feather=\"check-square\" class=\"align-text-bottom\" id = \"Header_Agreements\"></span>",
            "label": "Agreements"
          },
          {
            "url": "/relationships",
            "icon": "<span data-feather=\"table\" class=\"align-text-bottom\" id = \"Header_Relationships\"></span>",
            "label": "Relationships"
          },
          {
            "url": "/channels",
            "icon": "<span data-feather=\"tv\" class=\"align-text-bottom\" id = \"Header_Channels\"></span>",
            "label": "Channels"
          },
          {
            "url": "/settings",
            "icon": "<span data-feather=\"cpu\" class=\"align-text-bottom\" id = \"Header_Settings\"></span>",
            "label": "Settings"
          }],
        "SIGNOUT_CALL": {{ printf "signOut ('%s');" $cookiesDomain | quote }},
        "HEADER_JS_FILES": ["./js/common.js", "./js/quill@2.js"],
        "HEADER_CSS_FILES": ["./css/quill@2.bubble.css", "./css/quill@2.snow.css"]
      },
      "routePermissions": {
        "/agreements": "public",
        "/approvals": "mod",
        "/bankAccounts": "public",
        "/budgets": "public",
        "/channel": "public",
        "/channels": "admin",
        "/expenses": "public",
        "/forgot": "public",
        "/income": "public",
        "/": "public",
        "/login": "public",
        "/moderators": "mod",
        "/project": "public",
        "/projects": "public",
        "/proposals": "public",
        "/register": "public",
        "/relationships": "public",
        "/resetPassword": "public",
        "/settings": "admin",
        "/thankYou": "public",
        "/users": "mod",
        "/verify": "public"
      },
      "siteKey": {{ default "" .Values.freelightDAO_frontend.recaptchaSiteKey | quote }},
      "botBlocker": {{ .Values.botBlocker.enabled }}
    }
{{- end -}}
{{- end -}}
