{{- if .Values.garnetPubSub.deploy }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "freelight-dao.fullname" . }}-garnet-pubsub
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "garnet-pubsub") .) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "freelight-dao.selectorLabels" (merge (dict "SelectorName" "garnet-pubsub") .) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "freelight-dao.selectorLabels" (merge (dict "SelectorName" "garnet-pubsub") .) | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imageSettings.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imageSettings.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "freelight-dao.serviceAccountName" . }}-garnet-pubsub-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: garnet-pubsub
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.garnetPubSub.image }}"
          imagePullPolicy: {{ .Values.imageSettings.pullPolicy }}
          ports:
            - name: garnet-pubsub
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 20
            periodSeconds: 2
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}