{{- $frontend := merge (dict "Component" "frontend") . -}}
{{- $frontendName := include "freelight-auth.componentFullname" $frontend -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "freelight-auth.fullname" . }}
  labels:
    {{- include "freelight-auth.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: {{ .Values.httpRoute.gateway.name }}
      {{- if .Values.httpRoute.gateway.namespace }}
      namespace: {{ .Values.httpRoute.gateway.namespace }}
      {{- end }}
      {{- if .Values.certManager.enabled }}
      sectionName: https
      {{- end }}
  hostnames:
    {{- range .Values.freelightAuth_frontend.httpRoute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  rules:
    - backendRefs:
        - name: {{ $frontendName }}
          port: 80
