{{- if .Values.certManager.enabled }}
{{- if not .Values.certManager.clusterIssuer }}
{{- $fullName := include "freelight-docs.fullname" . }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ $fullName }}-issuer
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ $fullName }}-private-key
    solvers:
    - selector: {}
      {{- if eq .Values.certManager.solver "dns01" }}
      dns01:
        {{- toYaml .Values.certManager.dns01 | nindent 8 }}
      {{- else }}
      http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: {{ .Values.httpRoute.gateway.name }}
            {{- if .Values.httpRoute.gateway.namespace }}
            namespace: {{ .Values.httpRoute.gateway.namespace }}
            {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
