{{- if .Values.dicebear.deploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "freelight-dao.fullname" . }}-dicebear-deployment
  labels:
    {{- include "freelight-dao.labels" (merge (dict "SelectorName" "dicebear") .) | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "freelight-dao.selectorLabels" (merge (dict "SelectorName" "dicebear") .) | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "freelight-dao.selectorLabels" (merge (dict "SelectorName" "dicebear") .) | nindent 8 }}
	{{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imageSettings.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.imageSettings.pullSecrets }}
      {{- end }}
      serviceAccountName: {{ include "freelight-dao.serviceAccountName" . }}-dicebear-sa
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: dicebear
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.dicebear.image }}"
          imagePullPolicy: {{ .Values.imageSettings.pullPolicy }}
          ports:
            - name: dicebear-api
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /8.x/pixel-art/svg
              port: dicebear-api
          readinessProbe:
            httpGet:
              path: /8.x/pixel-art/svg
              port: dicebear-api
          resources:
            {{- toYaml .Values.dicebear.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}